# Generated by Django 4.2.13 on 2024-10-26 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wiki", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wikipage",
            options={
                "ordering": ["title"],
                "verbose_name": "Wiki Page",
                "verbose_name_plural": "Wiki Pages",
            },
        ),
        migrations.AlterModelOptions(
            name="wikirevision",
            options={
                "ordering": ["-edited_at"],
                "verbose_name": "Wiki Revision",
                "verbose_name_plural": "Wiki Revisions",
            },
        ),
        migrations.AlterField(
            model_name="wikipage",
            name="content",
            field=models.TextField(
                help_text="The content of the wiki page. Markdown formatting is supported."
            ),
        ),
        migrations.AlterField(
            model_name="wikipage",
            name="creator",
            field=models.ForeignKey(
                help_text="The user who created this page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_pages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="wikipage",
            name="last_editor",
            field=models.ForeignKey(
                help_text="The last user to edit this page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="edited_pages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="wikirevision",
            name="comment",
            field=models.CharField(
                blank=True,
                help_text="A brief description of the changes made in this revision.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="wikirevision",
            name="content",
            field=models.TextField(help_text="The content of this revision."),
        ),
        migrations.AlterField(
            model_name="wikirevision",
            name="editor",
            field=models.ForeignKey(
                help_text="The user who made this revision.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="wikirevision",
            name="page",
            field=models.ForeignKey(
                help_text="The wiki page this revision belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisions",
                to="wiki.wikipage",
            ),
        ),
    ]
