# Generated by Django 4.2.13 on 2024-10-26 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0002_alter_wikipage_options_alter_wikirevision_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="featured/")),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "page",
                    models.OneToOneField(
                        help_text="The wiki page this featured image belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_image",
                        to="wiki.wikipage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
