# Generated by Django 4.2.13 on 2024-10-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0004_featuredimage_banner_featuredimage_show_texture_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="featuredimage",
            name="active",
        ),
        migrations.RemoveField(
            model_name="featuredimage",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="featuredimage",
            name="description",
        ),
        migrations.RemoveField(
            model_name="featuredimage",
            name="title",
        ),
        migrations.AddField(
            model_name="featuredimage",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="Mark this as a featured article"
            ),
        ),
    ]
