# Generated by Django 4.2.13 on 2024-10-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0005_remove_featuredimage_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="featuredimage",
            name="banner_url",
            field=models.URLField(
                blank=True,
                help_text="Or provide a URL to a banner image",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="featuredimage",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Or provide a URL to a background image",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="featuredimage",
            name="banner",
            field=models.ImageField(
                blank=True,
                help_text="Upload a banner image",
                null=True,
                upload_to="banners/",
            ),
        ),
        migrations.AlterField(
            model_name="featuredimage",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a background image for the page header",
                null=True,
                upload_to="featured/",
            ),
        ),
    ]
