# Generated by Django 4.2.13 on 2024-10-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0006_featuredimage_banner_url_featuredimage_image_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="featuredimage",
            name="banner_url",
        ),
        migrations.RemoveField(
            model_name="featuredimage",
            name="image_url",
        ),
        migrations.AlterField(
            model_name="featuredimage",
            name="banner",
            field=models.ImageField(
                blank=True,
                help_text="Upload or provide URL for banner image",
                null=True,
                upload_to="banners/",
            ),
        ),
        migrations.AlterField(
            model_name="featuredimage",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload or provide URL for background image",
                null=True,
                upload_to="featured/",
            ),
        ),
    ]
