# Generated by Django 4.2.13 on 2024-10-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0007_remove_featuredimage_banner_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikipage",
            name="right_content",
            field=models.TextField(
                blank=True,
                help_text="Optional content for the right sidebar. Leave empty to hide sidebar.",
                null=True,
            ),
        ),
    ]
