# Generated by Django 4.2.13 on 2024-10-30 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0008_wikipage_right_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="featuredimage",
            name="is_featured",
        ),
        migrations.AddField(
            model_name="wikipage",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Show this article in the featured articles list",
            ),
        ),
        migrations.AlterField(
            model_name="featuredimage",
            name="page",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="featured_image",
                to="wiki.wikipage",
            ),
        ),
    ]
