# Generated by Django 4.2.13 on 2024-10-30 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0009_remove_featuredimage_is_featured_and_more"),
        ("wiki", "0009_wikipage_is_featured"),
        ("wiki", "new_migration"),
    ]

    operations = []
