# Generated by Django 4.2.13 on 2024-10-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0010_merge_20241030_0207"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikipage",
            name="related_to",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select articles that are related to this one",
                related_name="related_from",
                to="wiki.wikipage",
            ),
        ),
        migrations.AlterField(
            model_name="wikipage",
            name="right_content",
            field=models.TextField(
                blank=True,
                help_text="Optional content for the right sidebar. Leave empty to hide.",
                null=True,
            ),
        ),
    ]
