# Generated by Django 4.2.13 on 2024-10-30 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0003_create_default_site"),
        ("wiki", "0011_wikipage_related_to_alter_wikipage_right_content"),
    ]

    operations = []
