# Generated by Django 4.2.13 on 2024-08-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wod20th", "0023_shapeshifterform"),
    ]

    operations = [
        migrations.AddField(
            model_name="shapeshifterform",
            name="shift_message",
            field=models.TextField(
                blank=True,
                help_text="Custom message to display when shifting into this form. Use {name} for character name.",
            ),
        ),
    ]
