# Generated by Django 4.2.13 on 2024-08-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wod20th", "0024_shapeshifterform_shift_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shapeshifterform",
            name="shift_message",
        ),
        migrations.AddField(
            model_name="shapeshifterform",
            name="form_message",
            field=models.TextField(
                blank=True, help_text="Message to display when this form is assumed."
            ),
        ),
    ]
