# Generated by Django 4.2.14 on 2024-08-12 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "0014_defaultobject_defaultcharacter_defaultexit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("order", models.IntegerField(default=7)),
                ("infrastructure", models.IntegerField(default=8)),
                ("resolve", models.IntegerField(default=6)),
                ("resources", models.JSONField(default=dict)),
                (
                    "overseer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="districts_overseen",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proxies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="districts_proxied",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="districts",
                        to="objects.objectdb",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Neighborhood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("order", models.IntegerField(default=7)),
                ("infrastructure", models.IntegerField(default=7)),
                ("resolve", models.IntegerField(default=6)),
                (
                    "overseer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="neighborhoods_overseen",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proxies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="neighborhoods_proxied",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="neighborhoods",
                        to="objects.objectdb",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("importance", models.IntegerField(default=5)),
                (
                    "landlord",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sites_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "neighborhood",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="oss.neighborhood",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sites",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "tenants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="sites_tenanted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("dice_pool", models.CharField(max_length=255)),
                ("downtime_cost", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="TaskInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed", models.BooleanField(default=False)),
                (
                    "neighborhoods",
                    models.ManyToManyField(
                        related_name="task_instances", to="oss.neighborhood"
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="task_instances", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "sites",
                    models.ManyToManyField(
                        blank=True, related_name="task_instances", to="oss.site"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="oss.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("order", models.IntegerField(default=7)),
                ("infrastructure", models.IntegerField(default=8)),
                ("resolve", models.IntegerField(default=6)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectors",
                        to="oss.district",
                    ),
                ),
                (
                    "overseer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sectors_overseen",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proxies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="sectors_proxied",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sectors",
                        to="objects.objectdb",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Outcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("support_rating", models.IntegerField(default=0)),
                ("effects", models.JSONField(default=list)),
                (
                    "tasks",
                    models.ManyToManyField(related_name="outcomes", to="oss.task"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OSSEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("resolved", models.BooleanField(default=False)),
                (
                    "neighborhoods",
                    models.ManyToManyField(
                        related_name="events", to="oss.neighborhood"
                    ),
                ),
                (
                    "outcomes",
                    models.ManyToManyField(related_name="events", to="oss.outcome"),
                ),
                (
                    "selected_outcome",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="selected_for_events",
                        to="oss.outcome",
                    ),
                ),
                (
                    "sites",
                    models.ManyToManyField(
                        blank=True, related_name="events", to="oss.site"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="neighborhood",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="neighborhoods",
                to="oss.sector",
            ),
        ),
    ]
